# Generated by Django 2.2.7 on 2019-12-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='document',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='abstract',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='slug', max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
